### ISSUE TITLE
Error installing AXElements on OS X 10.10

### ISSUE THREAD

**Issue by EricTran5791** [AXElements/AXElements#12]
We've run into an issue when trying to install AXElements on a new machine. The OS X is 10.10.1, the gcc version is 4.2.1, and the Ruby version is 2.0.0.

To note, we had AXElements installed on other machines when they were running OS X 10.9 and it is still functional after upgrading to OS X 10.10.

````
sudo gem install AXElements
Building native extensions.  This could take a while...
ERROR:  Error installing AXElements:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
creating Makefile

make "DESTDIR="
compiling core.c
core.c:142:4: error: values of type 'AXError' should not be used as format arguments; add an explicit cast to 'int' instead [-Werror,-Wformat]
                 code
                 ^~~~
                 (int)
1 error generated.
make: *** [core.o] Error 1


Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/accessibility_core-0.4.3 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/accessibility_core-0.4.3/ext/accessibility/core/gem_make.out
````

Any assistance is greatly appreciated!

**Comment by ferrous26** [comment]
I have had no trouble installing AXElements with non-system ruby (i.e. from RVM), though this error seems related to the OS X SDK. 

I will look into it a bit more, but it looks like an easy fix in one of the C extensions.

**Comment by ferrous26** [comment]
AXElements 7.0.0.pre2 should address compilation issues.

```bash
sudo gem install AXElements --pre
```
