### ISSUE TITLE
Posting keyboard events is deprecated in 10.9 and later

### ISSUE THREAD

**Issue by bomberstudios** [AXElements/AXElements#14]
We're trying to test some mouse interaction using code in this form:

```ruby
hold_modifier "\\OPTION" do
  drag_mouse_to [650,250]
end
```

and we're getting this error:

```
Failure/Error: hold_modifier "\\OPTION" do
     RuntimeError:
       Posting keyboard events is deprecated in 10.9 and later
```

Is there any plan to work around this issue? Not being able to test this behaviour is sort of a deal breaker for us : /

Thanks in advance!

**Comment by bomberstudios** [comment]
Also, should we file this in `accessibility_core`?

**Comment by ferrous26** [comment]
The error is coming from core, but the change needs to be made in AXElements. This should be fixable, I will need try a couple of things out.

**Comment by bomberstudios** [comment]
Yay, thanks!

**Comment by ferrous26** [comment]
This should be fixed in 7.0.0.pre4

**Comment by bomberstudios** [comment]
Übercool! Thanks a lot!

**Comment by bomberstudios** [comment]
I just updated AXElements to pre4, and I have tried this (`@sketch` is a reference to our app, `draw_rectangle` is a custom helper):

```ruby
draw_rectangle [300,300], [100,100]

move_mouse_to [350,350]
@sketch.hold_modifier "\\OPTION" do
  drag_mouse_to [500,350]
end
```

This doesn't throw an error, but it doesn't look like Option is actually held while dragging the mouse to [500,350] (it should duplicate a layer in our app, but this code just moves it).

Any idea what we might be doing wrong?

**Comment by bomberstudios** [comment]
I AM CRYING TEARS OF JOY!

It now works beautifully, thanks a lot for fixing this : )

:heart:
