### ISSUE TITLE
Using ax_elements breaks empty Hash

### ISSUE THREAD

**Issue by abstiles** [AXElements/AXElements#9]
Doing `require 'ax_elements'` breaks the functionality of the built-in Hash type when given an empty list. Observe:

```irb
irb(main):001:0> Hash[[]]
=> {}
irb(main):002:0> require 'ax_elements'
=> true
irb(main):003:0> Hash[[]]
TypeError: can't convert Array to Hash (Array#to_hash gives Array)
        from (irb):3:in `[]'
        from (irb):3
        from /usr/bin/irb:12:in `<main>'
```

Notably, this also breaks the Nokogiri gem, which ends up raising this same error when using any of the xpath-like methods due to a call to Hash[] with a possibly empty list.

I am testing this with Ruby 2.0.0 and AXElements 6.0.0 running on OS X 10.9.

**Comment by ferrous26** [comment]
Should be all fixed now. Available in v7.0.0.pre3
